//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoAlumnosEgresados2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exalumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public exalumno()
        {
            this.historialacademicoes = new HashSet<historialacademico>();
            this.historialempleos = new HashSet<historialempleo>();
            this.publicacionesantiguas = new HashSet<publicacionesantigua>();
            this.publicaciones = new HashSet<publicacione>();
        }
    
        public string noControl { get; set; }
        public string nombre { get; set; }
        public string segundoNombre { get; set; }
        public string apellido { get; set; }
        public string segundoApellido { get; set; }
        public string correo { get; set; }
        public string clave { get; set; }
        public string idCarrera { get; set; }
        public string telefono { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public System.DateTime fechaEgreso { get; set; }
        public string rutaImg { get; set; }
    
        public virtual carrera carrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historialacademico> historialacademicoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historialempleo> historialempleos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<publicacionesantigua> publicacionesantiguas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<publicacione> publicaciones { get; set; }
    }
}
