//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoAlumnosEgresados2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historialacademico
    {
        public int idhistorialacademico { get; set; }
        public string noControl { get; set; }
        public string tituloH { get; set; }
        public string descripcionH { get; set; }
        public Nullable<System.DateTime> fechaH { get; set; }
        public string rutaImg { get; set; }
    
        public virtual exalumno exalumno { get; set; }
    }
}
