//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoAlumnosEgresados2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historialempleo
    {
        public int idEmpleo { get; set; }
        public string noControle { get; set; }
        public string empresa { get; set; }
        public string cargo { get; set; }
        public string descripcion { get; set; }
        public string rutalogo { get; set; }
    
        public virtual exalumno exalumno { get; set; }
    }
}
