//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoAlumnosEgresados2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class seguimiento2Entities : DbContext
    {
        public seguimiento2Entities()
            : base("name=seguimiento2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<carrera> carreras { get; set; }
        public virtual DbSet<exalumno> exalumnoes { get; set; }
        public virtual DbSet<historialacademico> historialacademicoes { get; set; }
        public virtual DbSet<historialempleo> historialempleos { get; set; }
        public virtual DbSet<publicacione> publicaciones { get; set; }
        public virtual DbSet<publicacionesantigua> publicacionesantiguas { get; set; }
    }
}
