//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoAlumnosEgresados2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicacione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public publicacione()
        {
            this.publicacionesantiguas = new HashSet<publicacionesantigua>();
        }
    
        public int idPublicacion { get; set; }
        public string noControlP { get; set; }
        public string titulop { get; set; }
        public string descripcionp { get; set; }
        public System.DateTime fechap { get; set; }
    
        public virtual exalumno exalumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<publicacionesantigua> publicacionesantiguas { get; set; }
    }
}
