//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguimientoAlumnosEgresados2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicacionesantigua
    {
        public int idpublicacionesAntiguas { get; set; }
        public int idPublicacion { get; set; }
        public string noControlpa { get; set; }
        public string titulopa { get; set; }
        public string descripcionpa { get; set; }
        public System.DateTime fechapa { get; set; }
    
        public virtual exalumno exalumno { get; set; }
        public virtual publicacione publicacione { get; set; }
    }
}
